account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy
from django.views.generic.base import TemplateView
from .forms import UserLoginForm, PwdResetForm, PwdResetConfirmForm
from . import views

app_name = 'account'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='account/login.html',
         form_class=UserLoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/account/login/'), name='logout'),
    path('register/', views.account_register, name='register'),
    path('activate/<slug:uidb64>/<slug:token>/',
         views.account_activate, name='activate'),
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(
            template_name="account/password_reset/password_reset_form.html",
            success_url='password_reset_email_confirm',
            subject_template_name='account/password_reset/password_reset_subject.txt',
            email_template_name="account/password_reset/password_reset_email.html",
            form_class=PwdResetForm,
        ),
        name="pwdreset",
    ),
    path('password_reset_confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(
        template_name='account/password_reset/password_reset_confirm.html',
        success_url=reverse_lazy('account:password_reset_complete'),
        form_class=PwdResetConfirmForm
    ),
        name='pwd_reset_confirm'),
    path(
        "password_reset/password_reset_email_confirm/",
        TemplateView.as_view(
            template_name="account/password_reset/reset_status.html"),
        name="password_reset_done",
    ),
    path(
        "password_reset_complete/",
        TemplateView.as_view(
            template_name="account/password_reset/reset_status.html"),
        name="password_reset_complete",
    ),
    path('wishlist/', views.wishlist, name='wishlist'),
    path('wishlist/add_to_wishlist/<int:id>/', views.add_to_wishlist, name='user_wishlist'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('profile/edit/', views.edit_details, name='edit_details'),
    path('profile/delete_user', views.delete_user, name='delete_user'),
    path('profile/delete_confirm', TemplateView.as_view(
        template_name='account/dashboard/delete_confirm.html'), name='delete_confirmation'),
    path('addresses/', views.view_address, name='addresses'),
    path('add_address/', views.add_address, name='add_address'),
    path('addresses/edit_address/<slug:id>/', views.edit_address, name='edit_address'),
    path('addresses/delete_address/<slug:id>/', views.delete_address, name='delete_address'),
    path('addresses/set_default/<slug:id>/', views.default_address, name='default_address'),
]

bookstore/urls.py
from django.urls import path
from .views import HomeView, BookDetailView, CategoryListView

app_name = 'bookstore'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('category/<slug:slug>/',  CategoryListView.as_view(), name='category_list'), 
    path('book/<slug:slug>/<slug:book_slug>/', BookDetailView.as_view(), name='single_book'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('bookstore.urls', namespace='bookstore')),
    path('account/', include('account.urls', namespace='account')),
    path('checkout/', include('checkout.urls', namespace='checkout')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
      {% block title %} BookStore - online книжный магазин {% endblock %}
    </title>
    <!-- <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1"
      crossorigin="anonymous"
    /> -->
    <link
      rel="stylesheet"
      href="{% static 'css/bootstrap.min.css' %}"
      type="text/css"
    />
    <link
      rel="stylesheet"
      href="{% static 'css/font-awesome.min.css' %}"
      type="text/css"
    />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Pacifico&family=Roboto:ital,wght@0,400;0,500;0,700;0,900;1,400;1,500;1,700&display=swap"
      rel="stylesheet"
    />
    <!-- <script
      src="https://code.jquery.com/jquery-3.5.1.min.js"
      integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
      crossorigin="anonymous"
    ></script> -->
    <!-- <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
      crossorigin="anonymous"
    ></script> -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css"
    />
    <link rel="stylesheet" href="{% static 'css/base.css' %}" />
    <link rel="stylesheet" href="{% block stylesheet %}{% endblock %}" />
  </head>
  <body>
    <div class="flex__wrapper">
      {% include 'header.html' %} 

      {% block content %} {% endblock %} 

      {% include 'footer.html' %}
    </div>

    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
  </body>
</html>

templates/detail.html
<div class="container">
    <div class="row mt-4">
        <div class="col-12">
          <h3>Bookovka знакомит с увлекательным миром книг</h3>
          <p>
            Чтение печатных книг — увлекательное занятие, которое на некоторое
            время утратило актуальность среди молодежи и детей, и все потому,
            что в нашу жизнь стремительно ворвались современные гаджеты —
            компьютеры, телефоны, планшеты. Организовывая книжный
            интернет-магазин с доставкой литературы по Украине, мы преследовали
            цель возродить интерес современного человека к печатным изданиям,
            предложить клиентам всех возрастов книги в разных жанровых
            исполнениях.
          </p>
          <hr />
          <h3>
            Самый большой интернет-магазин онлайн книг Украины (Киев) —
            электронный каталог
          </h3>
          <p>
            Чтобы купить книгу в онлайн магазине могли клиенты с разными
            литературными предпочтениями, в ассортимент включены издания из
            разряда: <br><br> художественной литературы — современную поэзию,
            классическую прозу, научную фантастику в обширном ассортименте
            предлагает украинский, электронный книжный интернет-магазин online
            (онлайн); увлечения, хобби — большой выбор книжек в
            интернет-магазине, которые помогут достигнуть совершенства в
            рукоделии, цветоводстве, огородничестве, научат начинающих кулинаров
            готовить повседневные и праздничные блюда, откроют секреты выживания
            на природе, подскажут что взять с собой в длительный туристический
            поход; познавательной литературы — благодаря книгам из этой
            категории книжного online (лайн) магазина каждый человек
            самосовершенствуется, расширяет кругозор, открывает новые горизонты,
            узнает интересные факты из жизни обитателей морских глубин и
            амазонских джунглей, раскрывает секреты космоса; электронные книги —
            украинский интернет-магазин специализируется на продаже книжных
            изданий русских, зарубежных писателей в цифровом формате, скачать
            книгу можно сразу на сайте; литература для детей — в нашем книжном
            магазине (г Киев) предложены самые лучшие печатные издания для
            малышей, дошкольников, читателей школьного возраста — хороший выбор
            сказок, стихотворений, иллюстрированных повестей. <br><br> Буковка — хороший,
            новый книжный интернет-магазин города Киев (Украина), который
            предлагает, кроме книг, купить на сайте пазлы и развивающие игры для
            детей, игрушки. В каталоге книжного магазина онлайн Украины
            присутствуют товары для спорта и активного отдыха — рюкзаки, сумки,
            электротранспорт, самокаты, одежда и средства защиты. <br><br> Книга — лучший
            подарок на День рождения, на мужской праздник или женский день.
            Воспользуйтесь предложениями Буковки, поздравьте друга, подарив ему
            украинские книжные издания в его любимом жанре. У нас интересная
            подборка картин по номерам в комплекте с красками. Друг, который
            интересуется живописью, будет приятно удивлен. Он с удовольствием
            раскрасит подаренный холст и разместит его на стене своей комнаты.
          </p>
          <hr style="color: red;">
        </div>
      </div>
</div>

templates/footer.html
{% load static %}

<footer class="footer">
  <div class="container">
    <div class="row" style="background:#dbf0f1;">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-6 g-1 mx-auto footer__top">
        <span class="col">О нас</span>
        <span class="col">Оплата</span>
        <span class="col">Доставка</span>
        <span class="col">Оптом</span>
        <span class="col">Помощь</span>
        <span class="col">Контакты</span>
      </div>
      <div class="col-12 footer__center">
        <div class="header__bottom__search col-lg-7 col-md-7">
          <div class="input-group mb-3">
            <input
              type="text"
              class="form-control"
              placeholder="Введите свой email"
              aria-label="Recipient's username"
              aria-describedby="button-addon2"
            />
            <button class="btn btn-warning" type="button" id="button-addon2">
              Подписаться
            </button>
          </div>
        </div>
        <div class="img__container" col-lg-5 col-md-5>
            <img src="{% static 'assets/visa-mastercard-logos.png' %}" alt="visa">
        </div>
      </div>
    </div>
  </div>
</footer>

templates/header.html
{% load static %}

<header class="header">
  <div class="container">
    <div class="row">
      <div class="header__top col-lg-12 col-md-12">
        <span>Работаем</span>
        <img src="{% static 'assets/Flag_of_Ukraine.png' %}" alt="#" />
        <span>для Вас!</span>
      </div>
    </div>
    <div class="row">
      <div class="header__center">
        <div class="header__center__left col-lg-8 d-flex">
          <div class="contact">
            <img src="{% static 'assets/tel.webp' %}" alt="" />
            <span>(044) 333-33-33</span>
          </div>
          <div class="contact">
            <img src="{% static 'assets/mts.webp' %}" alt="" />
            <span>(044) 333-33-33</span>
          </div>
          <div class="contact">
            <img src="{% static 'assets/kievstar.webp' %}" alt="" />
            <span>(044) 333-33-33</span>
          </div>
          <div class="contact">
            <img src="{% static 'assets/lifecell_logo.webp' %}" alt="" />
            <span>(044) 333-33-33</span>
          </div>
          <div class="contact">
            <img src="{% static 'assets/call.webp' %}" alt="" />
            <span>Обратная связь</span>
          </div>
        </div>
        <div class="header__center__right col-lg-4">
          <div class="location">
            <img src="{% static 'assets/location.webp' %}" alt="" />
            <span>Отследить заказ</span>
          </div>
          <ul class="navbar-nav navbar-nav text-center">
            <li class="nav-item dropdown">
              <a
                className="nav-link dropdown-toggle"
                role="button"
                data-bs-toggle="dropdown"
                aria-current="page"
                href="#"
                aria-expanded="false"
              >{% if user.is_authenticated %}
                Hi,  {{ request.user.username }}
                {% else %}
                Мой аккаунт
                {% endif %}
                <img src="{% static 'assets/user.webp' %}" alt="" />
              </a>
              <ul class="dropdown-menu p-2 mt-2">
                {% if user.is_authenticated %}
                <li class="register__open"><a href="{% url 'account:dashboard' %}">Мой профиль</a></li>
                <li><hr class="dropdown-divider"></li>
                <li class="register__open"><a href="{% url 'account:wishlist' %}">Список желаний</a></li>
                <li><hr class="dropdown-divider"></li>
                <li class="register__open"><a href="{% url 'account:logout' %}">Выйти</a></li>
                {% else %}
                <li class="register__open"><a href="{% url 'account:login' %}">Вoйти</a></li>
                {% endif %}
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="header__bottom">
        <a href="{% url 'bookstore:home' %}">
          <div class="header__bottom__logo col-lg-3 col-md-3">
          <img src="{% static 'assets/logo.jpeg' %}" alt="logo" />
        </div>
        </a>
        
        <div class="header__bottom__search col-lg-7 col-md-7">
          <div class="input-group mb-3">
            <input
              type="text"
              class="form-control"
              placeholder="Введите поисковой запрос"
              aria-label="Recipient's username"
              aria-describedby="button-addon2"
            />
            <button class="btn btn-warning" type="button" id="button-addon2">
              Поиск
            </button>
          </div>
        </div>
        <div class="header__bottom__cart col-lg-2 col-md-2">
          <img src="{% static 'assets/cart.webp' %}" alt="#" />
          <div class="count">4</div>
        </div>
      </div>
    </div>
  </div>
</header>