bookstore/urls.py
from django.urls import path
from .views import HomeView, BookDetailView, CategoryListView

app_name = 'bookstore'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('category/<slug:slug>/',  CategoryListView.as_view(), name='category_list'), 
    path('book/<slug:slug>/<slug:book_slug>/', BookDetailView.as_view(), name='single_book'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('bookstore.urls', namespace='bookstore')),
    path('account/', include('account.urls', namespace='account')),
    path('checkout/', include('checkout.urls', namespace='checkout')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

templates/bookstore/include/tags/category_tags_for_bigmenu.html
{% load mptt_tags %} 

{% recursetree list_category %} 
    {% if node.level == 0 %} 
        {% if not node.is_leaf_node %}
            <li class="dropdown dropend">
            <!-- Базовая категория, имеющая подкотегории -->
                <a
                    class="btn btn-outline dropdown-toggle"
                    href="{% url 'bookstore:category_list' node.slug %}"
                    role="button"
                    data-bs-toggle="dropdown"
                    aria-expanded="false"
                    style="background: inherit"
                >
                    {{node.name}}
                </a>
           
        {% else %}
            <li>
            <!-- Базовая категория, не имеющая подкотегорий -->
                <a 
                    class="btn btn-outline"
                    role="button"
                    href="{% url 'bookstore:category_list' node.slug %}"
                >
                    {{ node.name }}
                </a> 
            
        {% endif %} 
    {% else %} 
        {% if not node.is_leaf_node %}
            <li class="dropdown-submenu">
                <a
                    href="{% url 'bookstore:category_list' node.slug %}"
                    class="btn btn-outline dropdown-toggle"
                    data-toggle="dropdown"
                    role="button"
                    aria-haspopup="true"
                    aria-expanded="false"
                >
                    {{node.name}}
                </a>
              
        {% else %}
            <li>
                <a 
                    href="{% url 'bookstore:category_list' node.slug %}"
                >
                    {{ node.name }}
                </a>
                <li><hr class="dropdown-divider" style="background: lightgrey;" /></li>
        {% endif %} 
    {% endif %} 
            {% if not node.is_leaf_node %}
                <ul class="children dropdown-menu dropdown-menu-dark p-3">
                    {{ children }}
                </ul>
            {% endif %}
            </li>

{% endrecursetree %}