account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy
from django.views.generic.base import TemplateView
from .forms import UserLoginForm, PwdResetForm, PwdResetConfirmForm
from . import views

app_name = 'account'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='account/login.html',
         form_class=UserLoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/account/login/'), name='logout'),
    path('register/', views.account_register, name='register'),
    path('activate/<slug:uidb64>/<slug:token>/',
         views.account_activate, name='activate'),
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(
            template_name="account/password_reset/password_reset_form.html",
            success_url='password_reset_email_confirm',
            subject_template_name='account/password_reset/password_reset_subject.txt',
            email_template_name="account/password_reset/password_reset_email.html",
            form_class=PwdResetForm,
        ),
        name="pwdreset",
    ),
    path('password_reset_confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(
        template_name='account/password_reset/password_reset_confirm.html',
        success_url=reverse_lazy('account:password_reset_complete'),
        form_class=PwdResetConfirmForm
    ),
        name='pwd_reset_confirm'),
    path(
        "password_reset/password_reset_email_confirm/",
        TemplateView.as_view(
            template_name="account/password_reset/reset_status.html"),
        name="password_reset_done",
    ),
    path(
        "password_reset_complete/",
        TemplateView.as_view(
            template_name="account/password_reset/reset_status.html"),
        name="password_reset_complete",
    ),
    path('wishlist/', views.wishlist, name='wishlist'),
    path('wishlist/add_to_wishlist/<int:id>/', views.add_to_wishlist, name='user_wishlist'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('profile/edit/', views.edit_details, name='edit_details'),
    path('profile/delete_user', views.delete_user, name='delete_user'),
    path('profile/delete_confirm', TemplateView.as_view(
        template_name='account/dashboard/delete_confirm.html'), name='delete_confirmation'),
    path('addresses/', views.view_address, name='addresses'),
    path('add_address/', views.add_address, name='add_address'),
    path('addresses/edit_address/<slug:id>/', views.edit_address, name='edit_address'),
    path('addresses/delete_address/<slug:id>/', views.delete_address, name='delete_address'),
    path('addresses/set_default/<slug:id>/', views.default_address, name='default_address'),
]

bookstore/urls.py
from django.urls import path
from .views import HomeView, BookDetailView, CategoryListView

app_name = 'bookstore'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('category/<slug:slug>/',  CategoryListView.as_view(), name='category_list'), 
    path('book/<slug:slug>/<slug:book_slug>/', BookDetailView.as_view(), name='single_book'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('bookstore.urls', namespace='bookstore')),
    path('account/', include('account.urls', namespace='account')),
    path('checkout/', include('checkout.urls', namespace='checkout')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

bookstore/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from mptt.models import MPTTModel, TreeForeignKey
from ckeditor_uploader.fields import RichTextUploadingField


class Category(MPTTModel):
    class Meta:
        verbose_name = 'Рубрика'
        verbose_name_plural = 'Рубрики'

    name = models.CharField('рубрика', max_length=100,
                            help_text='* название основной рубрики книг')
    slug = models.SlugField(max_length=255)
    parent = TreeForeignKey('self', on_delete=models.SET_NULL,
                            blank=True, null=True, related_name='children')
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    class MPTTMeta:
        order_insertion_by = ['name']


class ProductType(models.Model):
    """Типы товаров, представленных на сайте"""

    name = models.CharField('тип товара', max_length=200,
                            unique=True, help_text='* Обязательное поле')
    is_active = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Тип товара'
        verbose_name_plural = 'Типы товара'

    def __str__(self):
        return self.name


class Publisher(models.Model):
    """Издательство"""

    name = models.CharField('Издательство', max_length=150)

    class Meta:
        verbose_name = 'Издательство'
        verbose_name_plural = 'Издательства'

    def __str__(self):
        return self.name


class Author(models.Model):
    name = models.CharField('автор', max_length=200)
    genre = models.CharField('жанр', max_length=200)
    about = RichTextUploadingField('Об авторе')

    class Meta:
        verbose_name = 'Автор'
        verbose_name_plural = 'Авторы'

    def __str__(self):
        return self.name


class BookSpecific(models.Model):
    """Модель названий спецификаций и свойств товара"""

    product_type = models.ForeignKey(ProductType, on_delete=models.RESTRICT)
    name = models.CharField('название характеристики', max_length=1200,
                            help_text='укажите название характеристики товара')

    class Meta:
        verbose_name = 'Характеристика товара'
        verbose_name_plural = 'Характеристики товара'

    def __str__(self):
        return self.name


class Book(models.Model):

    LANGUAGE_CHOICES = (
        ('ru', 'русский'),
        ('ua', 'украинский'),
        ('en', 'английский'),
        ('fr', 'французский'),
        ('de', 'немецкий'),
    )

    BINDING_CHOICES = (
        ('h', 'твердый'),
        ('p', 'мягкая обложка'),
        ('s', 'суперобложка'),
        ('i', 'интегральный'),
        ('c', 'картон'),
        ('l', 'кожаный'),
        ('fc', 'обложка с клапанами'),
    )

    AGE_CHOICES = (
        ('a', 'до 4-x'),
        ('b', '4-6'),
        ('с', '7-12'),
        ('d', '12-14'),
        ('e', '16+'),
        ('f', '18+'),
    )

    category = models.ForeignKey(
        Category, verbose_name='рубрика', on_delete=models.RESTRICT)
    product_type = models.ForeignKey(
        ProductType, verbose_name='тип товара', on_delete=models.RESTRICT)
    publisher = models.ForeignKey(
        Publisher, verbose_name='Издательство', on_delete=models.RESTRICT)
    author = models.ForeignKey(
        Author, verbose_name='автор', related_name='book', on_delete=models.RESTRICT)
    title = models.CharField('Название', max_length=150,
                         help_text='* Обязательное поле')
    image = models.ImageField(
        'изображение', help_text='добавьте изображение книги', upload_to='images/')
    description = RichTextUploadingField('описание книги')
    language = models.CharField(
        'язык', max_length=30, choices=LANGUAGE_CHOICES, default='русский')
    binding = models.CharField(
        'переплет', max_length=50, choices=BINDING_CHOICES)
    age = models.CharField('возраст', max_length=15,
                       choices=AGE_CHOICES, default='18+')
    pages = models.CharField('количество страниц', max_length=10)
    code_book = models.CharField('код товара', max_length=10, default=7)
    size = models.CharField('Размеры книги', max_length=20,
                        help_text='Укажите физический размер книги')
    slug = models.SlugField(max_length=255, unique=True)
    price = models.CharField('цена', max_length=4)
    discount = models.IntegerField(default=10)
    is_active = models.BooleanField(
        'доступность продукта', help_text='выберите доступность продукта', default=True)
    created = models.DateTimeField('создан', auto_now_add=True, editable=True)
    updated = models.DateTimeField('изменен', auto_now=True)
    user_wishlist = models.ManyToManyField(settings.AUTH_USER_MODEL)

    class Meta:
        verbose_name = 'Книга'
        verbose_name_plural = 'Книги'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('bookstore:single_book', kwargs={'slug': self.category.slug, 'book_slug': self.slug})

    def add_to_cart(self):
        return reverse('orders:add_to_cart', kwargs={'slug': self.category.slug, 'book_slug': self.slug})

    def get_discount_price(self):
        discount_price = self.price - (self.price * (self.discount/100))
        return discount_price


class BookSpecificValue(models.Model):
    """Модель значений спецификаций и свойств товара"""
    book = models.ForeignKey(Book, verbose_name='Книга', related_name='specifics',
                             on_delete=models.CASCADE)
    specification = models.ForeignKey(
        BookSpecific, verbose_name='Выберите из списка', on_delete=models.RESTRICT)
    value = models.CharField('описание характеристики', max_length=100)

    class Meta:
        verbose_name_plural = 'описание характеристик товара'

    def __str__(self):
        return ('выберите из списка')


class BookComment(models.Model):
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, verbose_name='автор', on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    body = models.TextField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.body

bookstore/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Book

class HomeView(ListView):
    model = Book
    paginate_by = 9
    template_name = 'bookstore/home.html'

class CategoryListView(ListView):
    model = Book
    template_name = 'bookstore/book_list.html'
    
    def get_queryset(self):
        return Book.objects.filter(category__slug=self.kwargs.get('slug')).select_related('category')

class BookDetailView(DetailView):
    model = Book
    context_object_name = 'book'
    slug_url_kwarg = 'book_slug'
    template_name = 'bookstore/single_book.html'

def order_summary(request):
    return render(request, 'bookstore/order_summary.html')


# Create your views here.

templates/bookstore/book_list.html
{% extends 'base.html' %} 
{% load static %} 
{% block content %}

<div class="category__list">
  <div class="container">
    <div class="row mt-4">
      {% for book in book_list %}
      <div class="col-12 mb-2">
        <h3 style="color: #ffc107;">Рубрика: {{ book.category.name }}</h3>
        <p style="font-size: 14;" class="text-muted">Количество наименований книг: {{forloop.counter}}</p>
      </div>
      {% include 'bookstore/include/sidebar_filter.html' %}
      <div class="col-md-9 col-lg-9">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3">
      
      <div class="col">
        <div class="card h-100">
          <a href="{{ book.get_absolute_url }}">
            <img class="card-img-top" src="{{ book.image.url }}" alt="test" />
          </a>

          <div class="card-body d-flex flex-column justify-content-between">
            <h6 class="card-title">{{ book.title }}</h6>
            <div class="product__price">
              <span>Цена:</span>
              <div class="price">{{book.price}} грн</div>
            </div>
          </div>
          <div class="card-footer mt-0" style="background: none; border: none">
            <a
              role="button"
              href="#"
              class="btn btn-warning"
              style="width: 100%"
              >В корзину</a
            >
          </div>
        </div>
      </div>
     
    </div>
      </div>
    </div>
     {% endfor %}
  </div>
</div>

{% include 'detail.html' %} {% endblock %}

templates/bookstore/home.html
{% extends 'base.html' %} 
{% load static %} 
{% block content %} 

{% include 'bookstore/include/big__menu.html' %}

<div class="home">
  <div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 mt-4 g-3">
      {% for book in book_list %}
      <div class="col">
        
           <div class="card h-100">
            <a href="{{ book.get_absolute_url }}">
               <img class="card-img-top" src="{{ book.image.url }}" alt="test" />
            </a>
         
          <div class="card-body d-flex flex-column justify-content-between">
            <h6 class="card-title">
              {{ book.title }}
            </h6>
            <div class="product__price">
              <span>Цена:</span>
              <div class="price">{{book.price}} грн</div>
            </div>
          </div>
             <div class="card-footer mt-0" style="background: none; border:none">
                 <a role="button" href="#" class="btn btn-warning" style="width: 100%;">В корзину</a>
             </div>
         </div>
      
       
      </div>
      {% endfor %}
    </div>
  </div>
</div>

{% include 'detail.html' %}

{% endblock %}

templates/bookstore/single_book.html
{% extends 'base.html' %} 
{% load static %} 
{% block content %}

<div class="single__book mt-5 mb-5">
  <div class="container">
    <div class="row">
      <div
        class="big__menu__right__header w-100"
        style="margin-top: -45px; margin-bottom: 30px"
      >
        <ul>
          <li>ПОДАРИТЬ КНИГУ</li>
          <li>НОВИНКИ</li>
          <li>БЕСТСЕЛЛЕРЫ</li>
          <li>ХИТЫ ПРОДАЖ</li>
          <li>БЛОГ</li>
        </ul>
      </div>
      {% include 'bookstore/include/sidebar.html' %}
      <div class="col-md-8 col-lg-8">
        <div class="row justify-content-between">
          <div class="col-md-4 col-lg-4 align-self-center">
            <img class="card-img-top" src="{{ book.image.url }}" alt="img" />
          </div>
          <div class="col-md-8 col-lg-8">
            <div class="single__book__wrapper" style="margin-left: 40px">
              <div class="single__book__header">
                <h4 class="text-start">{{ book.title }}</h4>
                {% if book.user_wishlist.exists %}
               <a role="button" class="btn btn-danger" href="{% url 'account:user_wishlist' book.id %}">Удалить</a>
               {% else %}
               <a role="button" class="btn btn-danger" href="{% url 'account:user_wishlist' book.id %}">В избранное</a>
               {% endif %}
              </div>
              
              <p class="single__book__author">{{ book.author }}</p>
              <div class="rating d-flex align-items-center">
                <div class="stars me-4">
                  <img src="{% static 'assets/starsrating.webp' %}" alt="">
                </div>
                <span class="comment text-muted">11 комментариев</span>
              </div>
              <div class="single__book__detail">
                <span class="pereplet">{{ book.get_binding_display }}</span>,
                <span class="single__book__detail__pages">{{ book.pages }}</span> страниц,
                <span class="single__book__detail__size">{{ book.size }} мм</span>
              </div>
              <hr />
              <div class="price__today">
                <span>Цена сегодня:</span>
                <span class="price">{{ book.get_discount_price }} грн</span>
                <button class="btn btn-warning">Купить</button>
              </div>
              <hr />
              <p class="discount">Скидка: <span>{{ book.discount }}%</span></p>
              <hr />
              <p class="regular__price">
                Регулярная цена: <span>{{ book.price }} грн</span>
              </p>
              <hr />
            </div>
          </div>
        </div>
        <div class="single__book__description">
          <h4 class="single__book__description__title">Описание книги</h4>
          <hr />
          <div class="single__book__description__about">
            <p>{{ book.description|safe }}</p>
            <div class="about__author">
              <h5>Об авторе:</h5>
              <p>{{ book.author.about|safe }}</p>
            </div>
          </div>
        </div>
          
        <div class="single__book__specific">
          <h4 class="single__book__description__title">Характеристики:</h4>
          <hr />
          {% for item in book.specifics.all %}
          <div class="single__book__specific__item">
            
            <div class="single__book__specific__item__left text-muted">
              {{ item.specification.name }}
            </div>
          
            <div class="single__book__specific__item__right">{{item.value}}</div>
          </div>
          {% endfor %}
         </div>
           <div class="comments">
          <div class="comments__header">
            <h4>Комментарии: <span>11</span></h4>
            <div class="product__rating">
              <span>Оценка товара:</span>
              <img src="{% static 'assets/starsrating.webp' %}" alt="stars">
            </div>
          </div>
          <form action="" method="post">
            <textarea name="comment" id="comment" class="w-100" rows="6" placeholder="Ваш комментарий"></textarea>
            <button class="btn btn-warning" type="submit">Комментировать</button>
          </form>
          <div class="comment__item">
            <span class="comment__item__author">Игорь Петров</span>
            <p class="commnt__item__text">
              Хочу замовити цю книгу. Ідеальна для читання перед святами, вже
              навіть по обкладинці захотілося Нового року та Різдва.
            </p>
            <div class="comment__item__date">
                <span class="date text-muted">26 Окт 2022</span>
                <span class="day text-muted">12:44</span>
            </div>
          </div>
          <div class="comment__item">
            <span class="comment__item__author">Игорь Петров</span>
            <p class="commnt__item__text">
              Хочу замовити цю книгу. Ідеальна для читання перед святами, вже
              навіть по обкладинці захотілося Нового року та Різдва.
            </p>
            <div class="comment__item__date">
                <span class="date text-muted">26 Окт 2022</span>
                <span class="day text-muted">12:44</span>
            </div>
          </div>
        </div>
      </div>
    </div>
    </div>
  </div>
</div>

{% endblock %}